FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# RUN pnpm config set enable-pre-post-scripts true
RUN pnpm add -g @pnpm/exec
RUN pnpm exec pnpm approve-builds prisma @prisma/engines

COPY package.json pnpm-lock.yaml ./


RUN pnpm install --frozen-lockfile --prod

COPY ./ ./

RUN pnpm db:generate

RUN pnpm build

CMD ["pnpm", "start:prod"]