import morgan from "morgan";
import { logger } from "../utils/logger.js";

export const loggerMiddleware = morgan(
  // format: string or callback, the function is expected to return a string that will be the log line, or undefined / null to skip logging
  // tokens contains HTTP data generated by Morgan
  function (tokens, req, res) {
    return JSON.stringify({
      method: tokens.method(req, res),
      url: tokens.url(req, res),
      status_code: Number.parseFloat(tokens.status(req, res) || "0"),
      content_length: tokens.res(req, res, "content-length"),
      response_time: Number.parseFloat(
        tokens["response-time"](req, res) || "0"
      ),
      user_agent: tokens["user-agent"](req, res),
      ip: "ip" in req ? req.ip : req.socket.remoteAddress,
      userId: "userId" in req ? req.userId : undefined,
      userRole: "userRole" in req ? req.userRole : undefined,
    });
  },
  // options object: immediate, skip, stream (here we use Winston logger to output log lines)
  {
    stream: {
      write: (message) => {
        const data = JSON.parse(message);
        logger.http(`incoming-request`, data);
      },
    },
  }
);
