@startuml Créer une fiche personnage
left to right direction
skinparam actorStyle awesome

actor Adhérent

rectangle "Espace membre" {
    usecase "Se connecter" as UC1
    usecase "Créer une fiche personnage" as UC2
    usecase "Associer une fiche personnage à une partie de jeu" as UC3
    usecase "Consulter la nouvelle fiche parmi la liste des fiches publiées" as UC4
}

Adhérent -- UC2

UC2 .> UC1 : <<include>>

UC2 .> UC3 : <<include>>

UC2 .> UC4 : <<extends>>

@enduml